-- Available state:
  -- call_grades (All the defined call grades)
  -- call_incidents (All the defined call incidents)
  -- call_types (All the defined call types)
  -- calls (All the defined calls)
  -- charges (All the defined charges)
  -- citizen_markers (All the defined citizen markers)
  -- citizens (All the defined citizens - for all users)
  -- locations (All the defined locations)
  -- unit_states (All the defined unit states)
  -- unit_types (All the defined unit types)
  -- units (All the defined units - active and inactive) 
  -- user_locations (All the locations of current users)
  -- user_ranks (All the defined user ranks)
  -- user_units (User -> unit assignments)
  -- users (All active users)
  -- vehicle_markers (All the defined vehicle markers)
  -- vehicle_models (All the defined vehicles)
  -- whitelist (All the whitelisted users)

local units = exports.cadvanced_mdt:state_get("calls")
dump_table(units)
